###################
### MY PROGRAMS ###
###################
# Set programs that you use
$terminal = ghostty
$fileManager = dolphin
$menu = wofi --show drun

source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces.conf
